# Generated by Django 3.0.2 on 2020-12-08 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='about',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='about',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовка'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='shops',
            name='slogan_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='shops',
            name='slogan_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='shops',
            name='slogan_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='shops',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название магазина'),
        ),
        migrations.AddField(
            model_name='shops',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название магазина'),
        ),
        migrations.AddField(
            model_name='shops',
            name='title_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='Название магазина'),
        ),
    ]
